# Some basic agreements are as below:
# 1. array value must not be null
# 2. name, path, data, build, bin, run must exist
# 3. data, build, bin, run have envs config and all the env name m-
#    -ust be 'dev' or 'prod'
# 4. build implementation must use `./data` directory
#    under the workspace to store all the files in `data` directive

gw:
  name: gw
  path: cmd/gw

  data:
    # data should be a directory under the workspace
    dev:
      - cmd/gw/config/dev.yaml
    prod:
      - cmd/gw/config/dev.yaml

  build:
    dev: go build ./cmd/gw
    prod: go build ./cmd/gw
  
  bin:
    dev:
      - ./gw
    prod:
      - ./gw

  run:
    dev: ./gw -config ./data/dev.yaml &> gw.log
    prod: ./gw -config ./data/dev.yaml &> gw.log

web:
  name: webclient
  path: web

  data:
    dev: []
    prod: []

  build: 
    dev: cd web && yarn build
    prod: cd web && yarn build --prod

  bin:
    dev:
      - web/build/*
    prod:
      - web/build/*

  run:
    dev: swank --path ./ &> web.log
    # prod env nginx is used to host the static files 
