package idgen

import "sync"

// IDGenerator generates unique IDs
// NOTE: uniqueness is not guarenteed for IDs generated by different generator instances
type IDGenerator struct {
	mtx sync.Mutex
	id  int64
}

// GenerateID returns a new ID
func (g *IDGenerator) GenerateID() int64 {
	g.mtx.Lock()

	g.id++
	id := g.id

	g.mtx.Unlock()
	return id
}
